language: python

sudo: required
dist: trusty

python:
 - "3.6"

before_install:
 - sed -i "s/KEY/$DISCORD_TOKEN/g" config/config.ini
 - sed -i '1 s/^\xef\xbb\xbf//' config/config.ini
 
install: 
 - pip install pipenv
 - pipenv install --dev

jobs:
  include:
    - stage: System Test
      script: bash ./test.sh
    - stage: Code Linting
      script: pipenv run yapf --diff --recursive .

notifications:
 email: false
