language: python

sudo: required
dist: xenial

python:
 - "3.6"

services:
  - docker

before_install:
 - sed -i "s/KEY/$DISCORD_TOKEN/g" config/config.ini

install:
 - pip install poetry
 - poetry install

script:
  - pip freeze > requirements.txt
  - docker build -t canary:latest .
  - docker run -v $(pwd):/mnt/canary canary:latest bash ./test.sh
  - docker run -v $(pwd):/mnt/canary canary:latest poetry run yapf --diff --recursive

notifications:
 email: false
