name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config cache-dir ~/.poetry
          poetry config virtualenvs.path ~/.poetry/venv

      - name: Poetry Install
        run: poetry install

      - name: Pip freeze
        run: pip3 freeze > requirements.txt
      
      - name: Run test
        run: bash ./test.sh